# Generated by Django 4.1.7 on 2023-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver_no', models.CharField(max_length=13)),
                ('msg', models.CharField(max_length=200)),
                ('hour', models.IntegerField(max_length=24)),
                ('min', models.IntegerField(max_length=60)),
            ],
        ),
    ]
