# Generated by Django 4.1.7 on 2023-03-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='msg',
            new_name='mssg',
        ),
    ]
